box/flaky

HISTORY.rst, README.rst, flaky/_flaky_plugin.py, flaky/flaky_nose_plugin.py, flaky/flaky_pytest_plugin.py, setup.py, test/test_flaky_nose_plugin.py, test/test_flaky_pytest_plugin.py, test/test_pytest_example.py, tox.ini
This allows the same test declaration to be collected multiple times without problems.
Also fixes a documentation error.
Fixes #36 Fixes #34 Fixes #33
=> Copy flaky attributes to collected tests.

flaky/flaky_nose_plugin.py, test/test_flaky_nose_plugin.py
Fixes #39.
Instead of rerunning a test as soon as it's identified as flaky and a failure, wait until after tearDown is called.
Only applies to the nose plugin.
=> Run flaky test reruns after tearDown.

HISTORY.rst, flaky/flaky_pytest_plugin.py, test/pytest_generate_example/__init__.py, test/pytest_generate_example/conftest.py, test/pytest_generate_example/test_pytest_generate_example.py, tox.ini
Fixes #51.
When using metafunc.parametrize to parametrize tests, the test name includes information about the parameters in square brackets.
However, these aren't "real" functions, so flaky wasn't able to find the @flaky decorator.
This commit adds code to look for square brackets and look for unparametrized functions.
=> Modify flaky to work with pytest parametrized tests.

HISTORY.rst, README.rst, flaky.iml, flaky/_flaky_plugin.py, flaky/flaky_nose_plugin.py, flaky/flaky_pytest_plugin.py, test/test_flaky_pytest_plugin.py
Now, passing --no-success-flaky-report will cause flaky to only
report about test failures.
=> Add command line option to shorten the flaky report.

HISTORY.rst, README.rst, flaky/_flaky_plugin.py, flaky/defaults.py, flaky/flaky_decorator.py, flaky/flaky_pytest_plugin.py, flaky/names.py, test/test_flaky_pytest_plugin.py
This commit adds a rerun_filter parameter to @flaky.
When flaky detects a failed test, before rerunning the test, it will call this function, only doing the rerun if it returns True.
=> Add ability to skip flaky rerun.

.coveragerc, AUTHORS.rst, CONTRIBUTING.rst, HISTORY.rst, flaky/flaky_nose_plugin.py, flaky/multiprocess_string_io.py, test/test_flaky_nose_plugin.py, test/test_multiprocess_string_io.py, tox.ini
Specifically, store the stream used in reports with a SyncManager ListProxy
object. Store the flaky results as items in the list, which are then written
out in the report at the end of the nosetests.
Before:
```
===Flaky Test Report===
===End Flaky Test Report===
```
Now:
```
===Flaky Test Report===
test_can_foo passed 1 out of the required 2 times. Running test again until it passes 2 times.
test_can_foo passed 2 out of the required 2 times. Success!
test_cannot_foo failed (1 runs remaining out of 2).
<type 'exceptions.AssertionError'>
'1' != u'2'
<traceback object at 0x20e2dd0>
test_cannot_foo passed 1 out of the required 1 times. Success!
===End Flaky Test Report===
```
=> Provide multiprocessing support for nose

flaky/flaky_nose_plugin.py
Fixed a bug: running with `--processes` gives error:
```
20:51:00     is_multiprocess = getattr(options, 'multiprocess_workers', 0) > 0
20:51:00 TypeError: unorderable types: str() > int()
```
=> fixed bug: running with nose multiprocess raised error

.pylintrc, flaky/_flaky_plugin.py, flaky/flaky_pytest_plugin.py, test/pytest_generate_example/conftest.py, test/pytest_generate_example/test_pytest_generate_example.py, test/test_flaky_pytest_plugin.py, test/test_pytest_example.py, test/test_pytest_options_example.py, tox.ini
This commit partially rewrites the pytest plugin so that retrying a test
includes setup and teardown of test fixtures.
This is a potentially **breaking change**, but it actually matches up
with how the nose plugin works and is probably what most users would want.
Fixes #53.
=> Refactor pytest plugin.

flaky/flaky_nose_plugin.py, test/test_nose/test_flaky_nose_plugin.py
Fixes #88
Nose plugin docs [0] say to return None from a hook to allow other
plugins to see the test. Flaky was returning False when it wanted
other plugins to see the test, which was causing incompatibility
with other plugins. This commit returns None from the addSuccess,
handleError, and handleFailure hooks where False would have been
returned (indicating that flaky was not handling the test).
[0]: http://nose.readthedocs.org/en/latest/plugins/interface.html#nose.plugins.base.IPluginInterface.addSuccess
=> Fix return values of nose plugin hooks.

HISTORY.rst, flaky/flaky_pytest_plugin.py, setup.cfg, setup.py, tox.ini
Previously, flaky monkey-patched the pytest runner's ``call_runtest_hook``
method. This was called by the runner's ``call_and_report`` method.
This commit monkey-patches the runner's ``call_and_report`` method so it
can inspect the result and avoid reporting tests that are going to be retried.
Fixes #91
Fixes #92
Fixes #94
=> Refactor flaky pytest plugin to avoid reporting test retries as passes.

flaky/flaky_pytest_plugin.py, setup.py, test/test_pytest/test_pytest_example.py
Fixes #96, which is a regression on #43.
When the py.test plugin was refactored in #76, the logic to not
retry Skipped tests was accidentally removed. This commit restores the logic
and adds a test so that we won't regress on this again.
=> Don't retry @skipped tests.

HISTORY.rst, flaky/_flaky_plugin.py, flaky/flaky_nose_plugin.py, flaky/flaky_pytest_plugin.py, setup.py
Don't assume that pytest Items have a module attribute.
Fixes #99 Fixes #101
=> Refactor getting test names and callables.

flaky/flaky_nose_plugin.py
Switches re-running tests to the afterTest method. More context in #70.
=> rerun using afterTest (fixes #70)

flaky/_flaky_plugin.py
This suppresses the following deprecation warnings:
```
/usr/lib/python3.5/site-packages/flaky/_flaky_plugin.py:356: DeprecationWarning: type argument to addoption() is a string 'int'. For parsearg this should be a type. (options: ('--max-runs',))
help="If --force-flaky is specified, we will run each test at "
/usr/lib/python3.5/site-packages/flaky/_flaky_plugin.py:366: DeprecationWarning: type argument to addoption() is a string 'int'. For parsearg this should be a type. (options: ('--min-passes',))
help="If --force-flaky is specified, we will run each test at "
```
=> Use type "int" for argparse type field instead of a string

flaky/flaky_pytest_plugin.py
=> pytest 4.1 compatibility

README.rst
Two backticks are used for code highlighting.
=> Fix RST code highlighting

HISTORY.rst, flaky/_flaky_plugin.py
This fixes #116 . In particular, if there are tests marked `flaky`, but they are deselected by pytest (e.g. with `-k` flag), then no report will be printed as well. In particular, that removes any extra output when running pytest on tests which do not use `flaky`, but `flaky` is installed.
I think that this change may use some end-to-end automatic tests, but I'm not sure where or how to add them. Any suggestions?
I've tested it locally, though: created a virtualenv with `pytest`, ran `setup.py install` and checked that the following file prints report when `py.test` without parameters and does not print report when run with `-k test_foo`:
```
from flaky import flaky
def test_foo():
assert 2 == 3
@flaky
def test_bar():
assert 2 == 3
```
=> Do not print report if there were no tests marked as 'flaky' (#116)

HISTORY.rst, flaky/flaky_pytest_plugin.py, test/test_pytest/test_flaky_pytest_plugin.py
A previous refactor (#74) enabled this, but I didn't notice.
Previously, flaky stored information about test reruns inside a
CallInfo subclass. call_runtest_hook was monkey patched so that
flaky could ensure that subclass was created. #74 moved that info
into the plugin, so the monkey patch was no longer doing anything
special.
However, over time, flaky's implementation diverged from pytest's.
This caused #139 and #156.
This commit removes the monkey patch, and flaky now uses pytest's
implementation, which fixes those issues and is more future proof.
=> Refactor pytest plugin to not monkey patch call_runtest_hook.

flaky/flaky_pytest_plugin.py
This causes tests that fail in setup to also be considered for re-running as requested in #135
=> Rerun flaky tests that fail in setup

requirements-dev.txt, test/test_flaky_plugin.py, test/test_multiprocess_string_io.py
With the development of the standard library it is not necessary to use external modules `mock` and `genty`, because the functionality is available by default.
=> Simplify flaky dependency
